version: "3.9"

services:
  database:
    image: postgres:15.6
    ports:
      - 5432:5432
    volumes:
      - ./infrastructure/container-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: springboot
      POSTGRES_PASSWORD: dblocal@spring
      POSTGRES_DB: springboot

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: diegormb@live.com
      PGADMIN_DEFAULT_PASSWORD: springboot
    ports:
      - "5050:80"